import { Country } from "@/types";
import { ClothingCategory, ProductSize } from "@/types/enum";


export const clothingCategories = [
  { value: ClothingCategory.Packet_Shirt, label: "Packet Shirts" },
  { value: ClothingCategory.Vintage_Shirt, label: "Vintage Shirts" },
  { value: ClothingCategory.Plain_Pant, label: "Plain Pants" },
  { value: ClothingCategory.Jogger, label: "Joggers" },
  { value: ClothingCategory.Senator, label: "Senators" },
  { value: ClothingCategory.Kaftan, label: "Kaftan" },
  { value: ClothingCategory.Agbada, label: "Agbada" },
];

export const productSizes = [
  { value: ProductSize.XS, label: "XS" },
  { value: ProductSize.S, label: "S" },
  { value: ProductSize.M, label: "M" },
  { value: ProductSize.L, label: "L" },
  { value: ProductSize.XL, label: "XL" },
  { value: ProductSize.XXL, label: "XXL" },
  { value: ProductSize.XXXL, label: "XXXL" },
  { value: ProductSize._28, label: "28" },
  { value: ProductSize._30, label: "30" },
  { value: ProductSize._32, label: "32" },
  { value: ProductSize._34, label: "34" },
  { value: ProductSize._36, label: "36" },
  { value: ProductSize._38, label: "38" },
  { value: ProductSize._40, label: "40" },
  { value: ProductSize._42, label: "42" },
  { value: ProductSize._44, label: "44" },
  { value: ProductSize._46, label: "46" },
  { value: ProductSize.one_size, label: "One Size" },
];

export const shippingLocation = [
  "International",
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
  "Federal Capital Territory"
];


export const worldCountries: Country[] = [
  {
    name: "Afghanistan",
    flag: "🇦🇫",
    phoneCode: "+93",
    countryCode: "AF",
  },
  { name: "Albania", flag: "🇦🇱", phoneCode: "+355", countryCode: "AL" },
  { name: "Algeria", flag: "🇩🇿", phoneCode: "+213", countryCode: "DZ" },
  { name: "Andorra", flag: "🇦🇩", phoneCode: "+376", countryCode: "AD" },
  { name: "Angola", flag: "🇦🇴", phoneCode: "+244", countryCode: "AO" },
  {
    name: "Antigua and Barbuda",
    flag: "🇦🇬",
    phoneCode: "+1-268",
    countryCode: "AG",
  },
  { name: "Argentina", flag: "🇦🇷", phoneCode: "+54", countryCode: "AR" },
  { name: "Armenia", flag: "🇦🇲", phoneCode: "+374", countryCode: "AM" },
  { name: "Australia", flag: "🇦🇺", phoneCode: "+61", countryCode: "AU" },
  { name: "Austria", flag: "🇦🇹", phoneCode: "+43", countryCode: "AT" },
  {
    name: "Azerbaijan",
    flag: "🇦🇿",
    phoneCode: "+994",
    countryCode: "AZ",
  },
  {
    name: "Bahamas",
    flag: "🇧🇸",
    phoneCode: "+1-242",
    countryCode: "BS",
  },
  { name: "Bahrain", flag: "🇧🇭", phoneCode: "+973", countryCode: "BH" },
  {
    name: "Bangladesh",
    flag: "🇧🇩",
    phoneCode: "+880",
    countryCode: "BD",
  },
  {
    name: "Barbados",
    flag: "🇧🇧",
    phoneCode: "+1-246",
    countryCode: "BB",
  },
  { name: "Belarus", flag: "🇧🇾", phoneCode: "+375", countryCode: "BY" },
  { name: "Belgium", flag: "🇧🇪", phoneCode: "+32", countryCode: "BE" },
  { name: "Belize", flag: "🇧🇿", phoneCode: "+501", countryCode: "BZ" },
  { name: "Benin", flag: "🇧🇯", phoneCode: "+229", countryCode: "BJ" },
  { name: "Bhutan", flag: "🇧🇹", phoneCode: "+975", countryCode: "BT" },
  { name: "Bolivia", flag: "🇧🇴", phoneCode: "+591", countryCode: "BO" },
  {
    name: "Bosnia and Herzegovina",
    flag: "🇧🇦",
    phoneCode: "+387",
    countryCode: "BA",
  },
  { name: "Botswana", flag: "🇧🇼", phoneCode: "+267", countryCode: "BW" },
  { name: "Brazil", flag: "🇧🇷", phoneCode: "+55", countryCode: "BR" },
  { name: "Brunei", flag: "🇧🇳", phoneCode: "+673", countryCode: "BN" },
  { name: "Bulgaria", flag: "🇧🇬", phoneCode: "+359", countryCode: "BG" },
  {
    name: "Burkina Faso",
    flag: "🇧🇫",
    phoneCode: "+226",
    countryCode: "BF",
  },
  { name: "Burundi", flag: "🇧🇮", phoneCode: "+257", countryCode: "BI" },
  {
    name: "Cabo Verde",
    flag: "🇨🇻",
    phoneCode: "+238",
    countryCode: "CV",
  },
  { name: "Cambodia", flag: "🇰🇭", phoneCode: "+855", countryCode: "KH" },
  { name: "Cameroon", flag: "🇨🇲", phoneCode: "+237", countryCode: "CM" },
  { name: "Canada", flag: "🇨🇦", phoneCode: "+1", countryCode: "CA" },
  {
    name: "Central African Republic",
    flag: "🇨🇫",
    phoneCode: "+236",
    countryCode: "CF",
  },
  { name: "Chad", flag: "🇹🇩", phoneCode: "+235", countryCode: "TD" },
  { name: "Chile", flag: "🇨🇱", phoneCode: "+56", countryCode: "CL" },
  { name: "China", flag: "🇨🇳", phoneCode: "+86", countryCode: "CN" },
  { name: "Colombia", flag: "🇨🇴", phoneCode: "+57", countryCode: "CO" },
  { name: "Comoros", flag: "🇰🇲", phoneCode: "+269", countryCode: "KM" },
  {
    name: "Republic of the Congo",
    flag: "🇨🇬",
    phoneCode: "+242",
    countryCode: "CG",
  },
  {
    name: "Congo, Democratic Republic of the",
    flag: "🇨🇩",
    phoneCode: "+243",
    countryCode: "CD",
  },
  {
    name: "Costa Rica",
    flag: "🇨🇷",
    phoneCode: "+506",
    countryCode: "CR",
  },
  { name: "Croatia", flag: "🇭🇷", phoneCode: "+385", countryCode: "HR" },
  { name: "Cuba", flag: "🇨🇺", phoneCode: "+53", countryCode: "CU" },
  { name: "Cyprus", flag: "🇨🇾", phoneCode: "+357", countryCode: "CY" },
  {
    name: "Czech Republic",
    flag: "🇨🇿",
    phoneCode: "+420",
    countryCode: "CZ",
  },
  { name: "Denmark", flag: "🇩🇰", phoneCode: "+45", countryCode: "DK" },
  { name: "Djibouti", flag: "🇩🇯", phoneCode: "+253", countryCode: "DJ" },
  {
    name: "Dominica",
    flag: "🇩🇲",
    phoneCode: "+1-767",
    countryCode: "DM",
  },
  {
    name: "Dominican Republic",
    flag: "🇩🇴",
    phoneCode: "+1-809",
    countryCode: "DO",
  },
  { name: "Ecuador", flag: "🇪🇨", phoneCode: "+593", countryCode: "EC" },
  { name: "Egypt", flag: "🇪🇬", phoneCode: "+20", countryCode: "EG" },
  {
    name: "El Salvador",
    flag: "🇸🇻",
    phoneCode: "+503",
    countryCode: "SV",
  },
  {
    name: "Equatorial Guinea",
    flag: "🇬🇶",
    phoneCode: "+240",
    countryCode: "GQ",
  },
  { name: "Eritrea", flag: "🇪🇷", phoneCode: "+291", countryCode: "ER" },
  { name: "Estonia", flag: "🇪🇪", phoneCode: "+372", countryCode: "EE" },
  { name: "Eswatini", flag: "🇸🇿", phoneCode: "+268", countryCode: "SZ" },
  { name: "Ethiopia", flag: "🇪🇹", phoneCode: "+251", countryCode: "ET" },
  { name: "Fiji", flag: "🇫🇯", phoneCode: "+679", countryCode: "FJ" },
  { name: "Finland", flag: "🇫🇮", phoneCode: "+358", countryCode: "FI" },
  { name: "France", flag: "🇫🇷", phoneCode: "+33", countryCode: "FR" },
  { name: "Gabon", flag: "🇬🇦", phoneCode: "+241", countryCode: "GA" },
  { name: "Gambia", flag: "🇬🇲", phoneCode: "+220", countryCode: "GM" },
  { name: "Georgia", flag: "🇬🇪", phoneCode: "+995", countryCode: "GE" },
  { name: "Germany", flag: "🇩🇪", phoneCode: "+49", countryCode: "DE" },
  { name: "Ghana", flag: "🇬🇭", phoneCode: "+233", countryCode: "GH" },
  { name: "Greece", flag: "🇬🇷", phoneCode: "+30", countryCode: "GR" },
  {
    name: "Grenada",
    flag: "🇬🇩",
    phoneCode: "+1-473",
    countryCode: "GD",
  },
  {
    name: "Guatemala",
    flag: "🇬🇹",
    phoneCode: "+502",
    countryCode: "GT",
  },
  { name: "Guinea", flag: "🇬🇼", phoneCode: "+224", countryCode: "GN" },
  {
    name: "Guinea-Bissau",
    flag: "🇬🇧",
    phoneCode: "+245",
    countryCode: "GW",
  },
  { name: "Guyana", flag: "🇬🇾", phoneCode: "+592", countryCode: "GY" },
  { name: "Haiti", flag: "🇭🇹", phoneCode: "+509", countryCode: "HT" },
  { name: "Honduras", flag: "🇭🇳", phoneCode: "+504", countryCode: "HN" },
  { name: "Hungary", flag: "🇭🇺", phoneCode: "+36", countryCode: "HU" },
  { name: "Iceland", flag: "🇮🇸", phoneCode: "+354", countryCode: "IS" },
  { name: "India", flag: "🇮🇳", phoneCode: "+91", countryCode: "IN" },
  { name: "Indonesia", flag: "🇮🇩", phoneCode: "+62", countryCode: "ID" },
  { name: "Iran", flag: "🇮🇷", phoneCode: "+98", countryCode: "IR" },
  { name: "Iraq", flag: "🇮🇶", phoneCode: "+964", countryCode: "IQ" },
  { name: "Ireland", flag: "🇮🇪", phoneCode: "+353", countryCode: "IE" },
  { name: "Israel", flag: "🇮🇱", phoneCode: "+972", countryCode: "IL" },
  { name: "Italy", flag: "🇮🇹", phoneCode: "+39", countryCode: "IT" },
  {
    name: "Jamaica",
    flag: "🇯🇲",
    phoneCode: "+1-876",
    countryCode: "JM",
  },
  { name: "Japan", flag: "🇯🇵", phoneCode: "+81", countryCode: "JP" },
  { name: "Jordan", flag: "🇯🇴", phoneCode: "+962", countryCode: "JO" },
  { name: "Kazakhstan", flag: "🇰🇿", phoneCode: "+7", countryCode: "KZ" },
  { name: "Kenya", flag: "🇰🇪", phoneCode: "+254", countryCode: "KE" },
  { name: "Kiribati", flag: "🇰🇷", phoneCode: "+686", countryCode: "KI" },
  { name: "Kuwait", flag: "🇰🇼", phoneCode: "+965", countryCode: "KW" },
  {
    name: "Kyrgyzstan",
    flag: "🇰🇬",
    phoneCode: "+996",
    countryCode: "KG",
  },
  { name: "Laos", flag: "🇱🇦", phoneCode: "+856", countryCode: "LA" },
  { name: "Latvia", flag: "🇱🇻", phoneCode: "+371", countryCode: "LV" },
  { name: "Lebanon", flag: "🇱🇧", phoneCode: "+961", countryCode: "LB" },
  { name: "Lesotho", flag: "🇱🇸", phoneCode: "+266", countryCode: "LS" },
  { name: "Liberia", flag: "🇱🇷", phoneCode: "+231", countryCode: "LR" },
  { name: "Libya", flag: "🇱🇾", phoneCode: "+218", countryCode: "LY" },
  {
    name: "Liechtenstein",
    flag: "🇱🇮",
    phoneCode: "+423",
    countryCode: "LI",
  },
  {
    name: "Lithuania",
    flag: "🇱🇹",
    phoneCode: "+370",
    countryCode: "LT",
  },
  {
    name: "Luxembourg",
    flag: "🇱🇺",
    phoneCode: "+352",
    countryCode: "LU",
  },
  {
    name: "Madagascar",
    flag: "🇲🇬",
    phoneCode: "+261",
    countryCode: "MG",
  },
  { name: "Malawi", flag: "🇲🇼", phoneCode: "+265", countryCode: "MW" },
  { name: "Malaysia", flag: "🇲🇾", phoneCode: "+60", countryCode: "MY" },
  { name: "Maldives", flag: "🇲🇻", phoneCode: "+960", countryCode: "MV" },
  { name: "Mali", flag: "🇲🇱", phoneCode: "+223", countryCode: "ML" },
  { name: "Malta", flag: "🇲🇹", phoneCode: "+356", countryCode: "MT" },
  {
    name: "Marshall Islands",
    flag: "🇲🇭",
    phoneCode: "+692",
    countryCode: "MH",
  },
  {
    name: "Mauritania",
    flag: "🇲🇦",
    phoneCode: "+222",
    countryCode: "MR",
  },
  {
    name: "Mauritius",
    flag: "🇲🇺",
    phoneCode: "+230",
    countryCode: "MU",
  },
  { name: "Mexico", flag: "🇲🇽", phoneCode: "+52", countryCode: "MX" },
  {
    name: "Micronesia",
    flag: "🇫🇲",
    phoneCode: "+691",
    countryCode: "FM",
  },
  { name: "Moldova", flag: "🇲🇩", phoneCode: "+373", countryCode: "MD" },
  { name: "Monaco", flag: "🇲🇨", phoneCode: "+377", countryCode: "MC" },
  { name: "Mongolia", flag: "🇲🇳", phoneCode: "+976", countryCode: "MN" },
  {
    name: "Montenegro",
    flag: "🇲🇪",
    phoneCode: "+382",
    countryCode: "ME",
  },
  { name: "Morocco", flag: "🇲🇦", phoneCode: "+212", countryCode: "MA" },
  {
    name: "Mozambique",
    flag: "🇲🇿",
    phoneCode: "+258",
    countryCode: "MZ",
  },
  { name: "Myanmar", flag: "🇲🇲", phoneCode: "+95", countryCode: "MM" },
  { name: "Namibia", flag: "🇳🇦", phoneCode: "+264", countryCode: "NA" },
  { name: "Nauru", flag: "🇦🇷", phoneCode: "+674", countryCode: "NR" },
  { name: "Nepal", flag: "🇳🇵", phoneCode: "+977", countryCode: "NP" },
  {
    name: "Netherlands",
    flag: "🇳🇱",
    phoneCode: "+31",
    countryCode: "NL",
  },
  {
    name: "New Zealand",
    flag: "🇳🇿",
    phoneCode: "+64",
    countryCode: "NZ",
  },
  {
    name: "Nicaragua",
    flag: "🇳🇮",
    phoneCode: "+505",
    countryCode: "NI",
  },
  { name: "Niger", flag: "🇳🇪", phoneCode: "+227", countryCode: "NE" },
  { name: "Nigeria", flag: "🇳🇬", phoneCode: "+234", countryCode: "NG" },
  {
    name: "North Macedonia",
    flag: "🇲🇰",
    phoneCode: "+389",
    countryCode: "MK",
  },
  { name: "Norway", flag: "🇳🇴", phoneCode: "+47", countryCode: "NO" },
  { name: "Oman", flag: "🇴🇲", phoneCode: "+968", countryCode: "OM" },
  { name: "Pakistan", flag: "🇵🇰", phoneCode: "+92", countryCode: "PK" },
  { name: "Palau", flag: "🇵🇼", phoneCode: "+680", countryCode: "PW" },
  {
    name: "Palestine",
    flag: "🇵🇸",
    phoneCode: "+970",
    countryCode: "PS",
  },
  { name: "Panama", flag: "🇵🇦", phoneCode: "+507", countryCode: "PA" },
  {
    name: "Papua New Guinea",
    flag: "🇵🇬",
    phoneCode: "+675",
    countryCode: "PG",
  },
  { name: "Paraguay", flag: "🇵🇾", phoneCode: "+595", countryCode: "PY" },
  { name: "Peru", flag: "🇵🇪", phoneCode: "+51", countryCode: "PE" },
  {
    name: "Philippines",
    flag: "🇵🇭",
    phoneCode: "+63",
    countryCode: "PH",
  },
  { name: "Poland", flag: "🇵🇱", phoneCode: "+48", countryCode: "PL" },
  { name: "Portugal", flag: "🇵🇹", phoneCode: "+351", countryCode: "PT" },
  { name: "Qatar", flag: "🇶🇦", phoneCode: "+974", countryCode: "QA" },
  { name: "Romania", flag: "🇷🇴", phoneCode: "+40", countryCode: "RO" },
  { name: "Russia", flag: "🇷🇺", phoneCode: "+7", countryCode: "RU" },
  { name: "Rwanda", flag: "🇷🇼", phoneCode: "+250", countryCode: "RW" },
  {
    name: "Saint Kitts and Nevis",
    flag: "🇰🇳",
    phoneCode: "+1-869",
    countryCode: "KN",
  },
  {
    name: "Saint Lucia",
    flag: "🇱🇨",
    phoneCode: "+1-758",
    countryCode: "LC",
  },
  {
    name: "Saint Vincent and the Grenadines",
    flag: "🇻🇨",
    phoneCode: "+1-784",
    countryCode: "VC",
  },
  { name: "Samoa", flag: "🇼🇸", phoneCode: "+685", countryCode: "WS" },
  {
    name: "San Marino",
    flag: "🇸🇲",
    phoneCode: "+378",
    countryCode: "SM",
  },
  {
    name: "Sao Tome and Principe",
    flag: "🇸🇹",
    phoneCode: "+239",
    countryCode: "ST",
  },
  {
    name: "Saudi Arabia",
    flag: "🇸🇦",
    phoneCode: "+966",
    countryCode: "SA",
  },
  { name: "Senegal", flag: "🇸🇳", phoneCode: "+221", countryCode: "SN" },
  { name: "Serbia", flag: "🇷🇸", phoneCode: "+381", countryCode: "RS" },
  {
    name: "Seychelles",
    flag: "🇸🇨",
    phoneCode: "+248",
    countryCode: "SC",
  },
  {
    name: "Sierra Leone",
    flag: "🇸🇱",
    phoneCode: "+232",
    countryCode: "SL",
  },
  { name: "Singapore", flag: "🇸🇬", phoneCode: "+65", countryCode: "SG" },
  { name: "Slovakia", flag: "🇸🇰", phoneCode: "+421", countryCode: "SK" },
  { name: "Slovenia", flag: "🇸🇮", phoneCode: "+386", countryCode: "SI" },
  {
    name: "Solomon Islands",
    flag: "🇸🇧",
    phoneCode: "+677",
    countryCode: "SB",
  },
  { name: "Somalia", flag: "🇸🇴", phoneCode: "+252", countryCode: "SO" },
  {
    name: "South Africa",
    flag: "🇿🇦",
    phoneCode: "+27",
    countryCode: "ZA",
  },
  {
    name: "South Korea",
    flag: "🇰🇷",
    phoneCode: "+82",
    countryCode: "KR",
  },
  {
    name: "South Sudan",
    flag: "🇸🇸",
    phoneCode: "+211",
    countryCode: "SS",
  },
  { name: "Spain", flag: "🇪🇸", phoneCode: "+34", countryCode: "ES" },
  { name: "Sri Lanka", flag: "🇱🇰", phoneCode: "+94", countryCode: "LK" },
  { name: "Sudan", flag: "🇸🇩", phoneCode: "+249", countryCode: "SD" },
  { name: "Suriname", flag: "🇸🇷", phoneCode: "+597", countryCode: "SR" },
  { name: "Sweden", flag: "🇸🇪", phoneCode: "+46", countryCode: "SE" },
  {
    name: "Switzerland",
    flag: "🇨🇭",
    phoneCode: "+41",
    countryCode: "CH",
  },
  { name: "Syria", flag: "🇸🇾", phoneCode: "+963", countryCode: "SY" },
  { name: "Taiwan", flag: "🇹🇼", phoneCode: "+886", countryCode: "TW" },
  {
    name: "Tajikistan",
    flag: "🇹🇯",
    phoneCode: "+992",
    countryCode: "TJ",
  },
  { name: "Tanzania", flag: "🇹🇿", phoneCode: "+255", countryCode: "TZ" },
  { name: "Thailand", flag: "🇹🇭", phoneCode: "+66", countryCode: "TH" },
  {
    name: "Timor-Leste",
    flag: "🇹🇱",
    phoneCode: "+670",
    countryCode: "TL",
  },
  { name: "Togo", flag: "🇹🇬", phoneCode: "+228", countryCode: "TG" },
  { name: "Tonga", flag: "🇹🇴", phoneCode: "+676", countryCode: "TO" },
  {
    name: "Trinidad and Tobago",
    flag: "🇹🇹",
    phoneCode: "+1-868",
    countryCode: "TT",
  },
  { name: "Tunisia", flag: "🇹🇳", phoneCode: "+216", countryCode: "TN" },
  { name: "Turkey", flag: "🇹🇷", phoneCode: "+90", countryCode: "TR" },
  {
    name: "Turkmenistan",
    flag: "🇹🇲",
    phoneCode: "+993",
    countryCode: "TM",
  },
  { name: "Tuvalu", flag: "🇹🇻", phoneCode: "+688", countryCode: "TV" },
  { name: "Uganda", flag: "🇺🇬", phoneCode: "+256", countryCode: "UG" },
  { name: "Ukraine", flag: "🇺🇦", phoneCode: "+380", countryCode: "UA" },
  {
    name: "United Arab Emirates",
    flag: "🇦🇪",
    phoneCode: "+971",
    countryCode: "AE",
  },
  {
    name: "United Kingdom",
    flag: "🇬🇧",
    phoneCode: "+44",
    countryCode: "GB",
  },
  {
    name: "United States of America",
    flag: "🇺🇸",
    phoneCode: "+1",
    countryCode: "US",
  },
  { name: "Uruguay", flag: "🇺🇾", phoneCode: "+598", countryCode: "UY" },
  {
    name: "Uzbekistan",
    flag: "🇺🇿",
    phoneCode: "+998",
    countryCode: "UZ",
  },
  { name: "Vanuatu", flag: "🇻🇺", phoneCode: "+678", countryCode: "VU" },
  {
    name: "Vatican City",
    flag: "🇻🇦",
    phoneCode: "+379",
    countryCode: "VA",
  },
  { name: "Venezuela", flag: "🇻🇪", phoneCode: "+58", countryCode: "VE" },
  { name: "Vietnam", flag: "🇻🇳", phoneCode: "+84", countryCode: "VN" },
  { name: "Yemen", flag: "🇾🇪", phoneCode: "+967", countryCode: "YE" },
  { name: "Zambia", flag: "🇿🇲", phoneCode: "+260", countryCode: "ZM" },
  { name: "Zimbabwe", flag: "🇿🇼", phoneCode: "+263", countryCode: "ZW" },
];
